In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent=dataset[['charges']]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.30,random_state=0)

In [3]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [4]:
scy=StandardScaler()
y_train=scy.fit_transform(y_train)
y_test=scy.transform(y_test)

In [5]:
import pickle
filename="finilized_model_decisiontreeregression.sav"

In [7]:
preinput_data = [[20, 35.2, 35000, 0, 1]]

In [8]:
preinput = sc.transform(preinput_data)

C:\Anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [9]:
preinput

array([[-1.39029200e+00,  7.13647492e-01,  2.90797108e+04,
        -9.76765571e-01,  1.98149332e+00]])

In [10]:
loaded_model=pickle.load(open("finilized_model_decisiontreeregression.sav",'rb'))
result=loaded_model.predict(preinput)

In [11]:
result

array([1.88336878])

In [12]:
preoutput=scy.inverse_transform([result])

In [13]:
preoutput

array([[35595.5898]])